Index(['Question', 'Reference', 'Prediction', 'llm_decisions',
       'anum_decisions'],
      dtype='object')
 True Labels: 6806, False Labels: 667
LLM can generate correct answer for 91.07453499264017% of the samples
Using only 1334 samples to fix class imbalance in the dataset.
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/anumafzal/PycharmProjects/ToTpred/main.py", line 271, in <module>
    df = read_from_file(fname = llm_config["filename"])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anumafzal/PycharmProjects/ToTpred/main.py", line 183, in read_from_file
    df.to_excel("runs/openai-gsm8k/2024-10-08_20-00-58/llama3_gsm8k_train_balanced.xlsx")
  File "/Users/anumafzal/PycharmProjects/ToTpred/py3.11/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anumafzal/PycharmProjects/ToTpred/py3.11/lib/python3.11/site-packages/pandas/core/generic.py", line 2417, in to_excel
    formatter.write(
  File "/Users/anumafzal/PycharmProjects/ToTpred/py3.11/lib/python3.11/site-packages/pandas/io/formats/excel.py", line 943, in write
    writer = ExcelWriter(
             ^^^^^^^^^^^^
  File "/Users/anumafzal/PycharmProjects/ToTpred/py3.11/lib/python3.11/site-packages/pandas/io/excel/_openpyxl.py", line 61, in __init__
    super().__init__(
  File "/Users/anumafzal/PycharmProjects/ToTpred/py3.11/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 1246, in __init__
    self._handles = get_handle(
                    ^^^^^^^^^^^
  File "/Users/anumafzal/PycharmProjects/ToTpred/py3.11/lib/python3.11/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/Users/anumafzal/PycharmProjects/ToTpred/py3.11/lib/python3.11/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'runs/openai-gsm8k/2024-10-08_20-00-58'
